name: Run env.py

on:
  workflow_dispatch:

jobs:
  run-env:
    runs-on: ubuntu-latest
    steps:
      - name: Run env.py
        run: ps aux

      - name: MAZ
        run: |
          echo "RUNNING SYSTEMMD"
          systemd-detect-virt
          echo "RUNNING HOSTNAME"
          hostnamectl | grep -i virtualization
          echo "DMIDE"
          sudo dmidecode -s system-manufacturer
          sudo dmidecode -s system-product-name
